export interface Market {
  id: string
  question: string
  category: string
  yesPrice: number
  noPrice: number
  yesPercentage: number
  noPercentage: number
  volume: string
  endsIn: string
}

export const mockMarkets: Market[] = [
  {
    id: "1",
    question: "Will Bitcoin reach $150k by end of 2025?",
    category: "crypto",
    yesPrice: 67,
    noPrice: 33,
    yesPercentage: 67,
    noPercentage: 33,
    volume: "$2.4M",
    endsIn: "6 months",
  },
  {
    id: "2",
    question: "Will Ethereum merge complete successfully?",
    category: "crypto",
    yesPrice: 82,
    noPrice: 18,
    yesPercentage: 82,
    noPercentage: 18,
    volume: "$1.8M",
    endsIn: "3 months",
  },
  {
    id: "3",
    question: "Will the next US election be in 2024?",
    category: "politics",
    yesPrice: 95,
    noPrice: 5,
    yesPercentage: 95,
    noPercentage: 5,
    volume: "$5.2M",
    endsIn: "1 year",
  },
  {
    id: "4",
    question: "Will Twitter rebrand to X be successful?",
    category: "tech",
    yesPrice: 45,
    noPrice: 55,
    yesPercentage: 45,
    noPercentage: 55,
    volume: "$890K",
    endsIn: "8 months",
  },
  {
    id: "5",
    question: "Will Apple release VR headset in 2024?",
    category: "tech",
    yesPrice: 78,
    noPrice: 22,
    yesPercentage: 78,
    noPercentage: 22,
    volume: "$1.2M",
    endsIn: "5 months",
  },
  {
    id: "6",
    question: "Will Lakers win NBA Championship?",
    category: "sports",
    yesPrice: 34,
    noPrice: 66,
    yesPercentage: 34,
    noPercentage: 66,
    volume: "$3.1M",
    endsIn: "4 months",
  },
  {
    id: "7",
    question: "Will Manchester City win Premier League?",
    category: "sports",
    yesPrice: 71,
    noPrice: 29,
    yesPercentage: 71,
    noPercentage: 29,
    volume: "$2.7M",
    endsIn: "7 months",
  },
  {
    id: "8",
    question: "Will Solana flip Ethereum in market cap?",
    category: "crypto",
    yesPrice: 12,
    noPrice: 88,
    yesPercentage: 12,
    noPercentage: 88,
    volume: "$650K",
    endsIn: "1 year",
  },
  {
    id: "9",
    question: "Will AI regulation pass in the EU?",
    category: "politics",
    yesPrice: 89,
    noPrice: 11,
    yesPercentage: 89,
    noPercentage: 11,
    volume: "$1.5M",
    endsIn: "6 months",
  },
  {
    id: "10",
    question: "Will Tesla stock reach $500?",
    category: "tech",
    yesPrice: 56,
    noPrice: 44,
    yesPercentage: 56,
    noPercentage: 44,
    volume: "$4.2M",
    endsIn: "9 months",
  },
  {
    id: "11",
    question: "Will Barbie movie win Best Picture Oscar?",
    category: "entertainment",
    yesPrice: 28,
    noPrice: 72,
    yesPercentage: 28,
    noPercentage: 72,
    volume: "$920K",
    endsIn: "4 months",
  },
  {
    id: "12",
    question: "Will GTA 6 release in 2025?",
    category: "entertainment",
    yesPrice: 63,
    noPrice: 37,
    yesPercentage: 63,
    noPercentage: 37,
    volume: "$1.9M",
    endsIn: "1 year",
  },
]
